# Generated by Django 4.1.4 on 2022-12-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tier", name="tierValue",),
        migrations.AddField(
            model_name="tier",
            name="tier",
            field=models.CharField(
                choices=[("1", "Tier 1"), ("2", "Tier 2"), ("3", "Market")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="grade",
            field=models.CharField(
                choices=[
                    ("AA", "Grade AA"),
                    ("A", "Grade A"),
                    ("B", "Grade B"),
                    ("Bk", "Grade Bk"),
                    ("C", "Grade C"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
