# Generated by Django 4.1.4 on 2023-01-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_tier_tiervalue_tier_tier_alter_product_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order", options={"ordering": ["-transactionTime"]},
        ),
        migrations.RemoveField(model_name="order", name="subtotal",),
        migrations.AddField(
            model_name="order", name="flag", field=models.BooleanField(null=True),
        ),
    ]
