# Generated by Django 4.1.4 on 2023-02-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_order_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(name="invoice", options={"ordering": ["id"]},),
    ]
