# Generated by Django 4.1.4 on 2023-02-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_invoice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="invoice", options={"ordering": ["-id"]},),
    ]
