# Generated by Django 4.1.4 on 2023-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_invoice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice", name="grandTotal", field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="summary",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
