# Generated by Django 4.1.4 on 2023-02-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_invoice_grandtotal_invoice_summary"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="creditBalance",),
    ]
