# Generated by Django 4.1.4 on 2023-02-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_customer_creditbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="companyAddress",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="companyName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="companyPhone",
            field=models.IntegerField(null=True),
        ),
    ]
