# Generated by Django 4.1.4 on 2023-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_customer_companyaddress_customer_companyname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="companyAddress",
            field=models.CharField(default="N/A", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="companyName",
            field=models.CharField(default="N/A", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="companyPhone",
            field=models.IntegerField(default="N/A", null=True),
        ),
    ]
