# Generated by Django 4.1.4 on 2023-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_customer_companyaddress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="flag", field=models.BooleanField(default=False),
        ),
    ]
