# Generated by Django 4.1.4 on 2023-02-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_order_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="companyPhone",
            field=models.IntegerField(null=True),
        ),
    ]
