# Generated by Django 4.1.4 on 2023-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_alter_customer_companyphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="N/A", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="N/A", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("Johor", "Johor"),
                    ("Kedah", "Kedah"),
                    ("Kelantan", "Kelantan"),
                    ("Malacca", "Malacca"),
                    ("Negeri Sembilan", "Negeri Sembilan"),
                    ("Pahang", "Pahang"),
                    ("Penang", "Penang"),
                    ("Perak", "Perak"),
                    ("Perlis", "Perlis"),
                    ("Sabah", "Sabah"),
                    ("Sarawak", "Sarawak"),
                    ("Selangor", "Selangor"),
                    ("Terengganu", "Terengganu"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
