# Generated by Django 4.1.4 on 2023-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_customer_address_customer_city_customer_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="postcode",
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
