# Generated by Django 4.1.4 on 2023-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_alter_customer_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
