# Generated by Django 4.1.4 on 2023-02-19 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_customer_email_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid phone number", regex="^\\d{3}-\\d{3}-\\d{4}$"
                    )
                ],
            ),
        ),
    ]
