# Generated by Django 4.1.4 on 2023-02-23 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\d{3}\\d{3}\\d{4}$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.customer",
            ),
        ),
    ]
