# Generated by Django 4.1.4 on 2023-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_alter_customer_phone_alter_order_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="tier",),
        migrations.AlterField(
            model_name="customer",
            name="tier",
            field=models.CharField(
                choices=[("1", "Tier 1"), ("2", "Tier 2"), ("3", "Market")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(name="Tier",),
    ]
