# Generated by Django 4.1.4 on 2023-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_remove_product_tier_alter_customer_tier_delete_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="discount", field=models.FloatField(default=1),
        ),
    ]
