# Generated by Django 4.1.4 on 2023-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_alter_customer_options_invoice_discountedtotal"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="summary",),
        migrations.AlterField(
            model_name="customer",
            name="tier",
            field=models.CharField(
                choices=[("1", "Tier 1"), ("2", "Tier 2"), ("3", "Market")],
                default="3",
                max_length=10,
            ),
        ),
    ]
