# Generated by Django 4.1.4 on 2023-02-25 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_alter_customer_companyaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="companyAddress",
            field=models.CharField(default="N/A", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="companyPhone",
            field=models.CharField(
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\d{3}\\d{3}\\d{4}$")
                ],
            ),
        ),
    ]
